app             = "rdap-root-server"
kill_signal     = "SIGINT"
kill_timeout    = 5
primary_region  = "lhr"
processes       = []

[experimental]
cmd             = ["/app/rdapd", "--root"]

[build]
dockerfile      = "Dockerfile"

[deploy]
strategy        = "rolling"

[http_service]
internal_port   = 8080
force_https     = true

[[http_service.checks]]
grace_period    = "60s"
interval        = "5s"
timeout         = "5s"
method          = "get"
path            = "/heartbeat"
protocol        = "http"
